config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :tags_neededs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :fan_user_styles

  resources :fan_style_definitions

  resources :user_badges

  resources :badges

  match '/scoreColumns',:controller=>'rate_columns',:action=>'columnName',via:[:get,:post]
  match '/changeViewColumn',:controller=>'rate_columns',:action=>'addNewColumn',via:[:get,:post]
  resources :rate_columns

  resources :fan_rates

  match 'skills/:q',:controller=>'skill_neededs',:action=>'skillProject',via:[:get],to: 'skill_neededs#index'
  resources :skill_neededs

  resources :skill_lists
  

  match 'paypal/:q',:controller=>'ipaypals',:action=>'index',via:[:get],to: 'ipaypals#index'
  resources :ipaypals

  match '/listFiles',:controller=>'sessions',:action=>'listfiles',via:[:get,:post]
  match '/aut/google_oauth2',:controller=>'sessions',:action=>'perform_sync',via:[:get,:post]
  match '/aut/google_oauth2/callback',:controller=>'sessions',:action=>'perform_sync_callback',via:[:get,:post]
  match '/aut/reset',:controller=>'sessions',:action=>'perform_reset',via:[:get,:post]
  match '/aut/permission',:controller=>'sessions',:action=>'givePermissionToFolder',via:[:get,:post]
  match '/aut/filepermission',:controller=>'sessions',:action=>'givePermissionToFile',via:[:get,:post]
  resources :sessions

  match '/tab/remove',:controller=>'tabmanagers',:action=>'tab_remove',via:[:get,:post]
  resources :tabmanagers

  resources :license_types

  
  match '/getUserRating',:controller=>'fan_users',:action=>'getUserRating',via:[:get,:post]
  match '/registerProcess',:controller=>'fan_users',:action=>'registerProcess',via:[:get,:post]
  match '/loginProcess',:controller=>'fan_users',:action=>'logProcess',via:[:get,:post]
  match '/logoutProcess',:controller=>'fan_users',:action=>'logoutProcess',via:[:get,:post]

  match '/notifications',:controller=>'fan_users',:action=>'notifications',via:[:get,:post]
  
  match '/setUserRating',:controller=>'fan_users',:action=>'setUserRating',via:[:get,:post]
  match '/user-style/:q',:controller=>'fan_users',:action=>'setUserStyle',via:[:get],:to=>'fan_user_styles#index'
  resources :fan_users

  match '/setTaskWorker', :controller=>'fan_tasks',:action=>'claimTask',via:[:get,:post]
  match '/setDemoFile', :controller=>'fan_tasks',:action=>'assignDemoFile',via:[:get,:post]
  match '/setTaskFile', :controller=>'fan_tasks',:action=>'assignFanTask',via:[:get,:post]
  match '/setDeliveryFile', :controller=>'fan_tasks',:action=>'assignFinalFile',via:[:get,:post]
  match '/submitFilesToFanimate', :controller=>'fan_tasks',:action=>'submitTask',via:[:get,:post]
  match '/attachPermission', :controller=>'fan_tasks',:action=>'changePermission',via:[:get,:post]
  match '/attachReferences', :controller=>'fan_tasks',:action=>'attachReferences',via:[:get,:post]
  match '/getSharedFilesAsync', :controller=>'fan_tasks',:action=>'getSharedFilesAsync',via:[:get,:post]
  match '/acceptTask', :controller=>'fan_tasks',:action=>'acceptTask',via:[:get,:post]
  match '/rejectTask', :controller=>'fan_tasks',:action=>'rejectTask',via:[:get,:post]
  resources :fan_tasks

  match '/getProjectTasks', :controller=>'fan_projects',:action=>'getProjectTasks',via:[:get,:post]
  match '/getProjectTabs', :controller=>'fan_projects',:action=>'getProjectTabs',via:[:get,:post]
  resources :fan_projects

  resources :fan_pivot_tasks

  resources :fan_files

  match '/getCurrentCategory',:controller=>'fan_categories',:action=>'getCategory',via:[:get,:post]
  match '/setCurrentCategory',:controller=>'fan_categories',:action=>'setCategory',via:[:get,:post]
  resources :fan_categories

  match '/search/:q',:controller=>'welcome',:action=>'search',via:[:get],to: 'welcome#_edit'

  match '/schedule',:controller=>'welcome',:action=>'schedule',via:[:get]
  root 'welcome#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/fan_category.rb
class FanCategory < ActiveRecord::Base
end

app/models/fan_file.rb
class FanFile < ActiveRecord::Base
end

app/models/fan_pivot_task.rb
class FanPivotTask < ActiveRecord::Base
end

app/models/fan_project.rb
class FanProject < ActiveRecord::Base
end

app/models/fan_rate.rb
class FanRate < ActiveRecord::Base
end

app/models/fan_task.rb
class FanTask < ActiveRecord::Base
end

app/models/fan_user.rb
class FanUser < ActiveRecord::Base
end

app/models/fan_user_style.rb
class FanUserStyle < ActiveRecord::Base
end

app/models/history.rb
class History < ActiveRecord::Base
end

app/models/ipaypal.rb
class Ipaypal < ActiveRecord::Base
end

app/models/license_type.rb
class LicenseType < ActiveRecord::Base
end

app/models/rate_column.rb
class RateColumn < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/skill_list.rb
class SkillList < ActiveRecord::Base
end

app/models/skill_needed.rb
class SkillNeeded < ActiveRecord::Base
end

app/models/tabmanager.rb
class Tabmanager < ActiveRecord::Base
end

app/models/tags_needed.rb
class TagsNeeded < ActiveRecord::Base
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: [:show, :edit, :update, :destroy]

  # GET /badges
  # GET /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1
  # GET /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges
  # POST /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to @badge, notice: 'Badge was successfully created.' }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1
  # PATCH/PUT /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to @badge, notice: 'Badge was successfully updated.' }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1
  # DELETE /badges/1.json
  def destroy
    @badge.destroy
    respond_to do |format|
      format.html { redirect_to badges_url, notice: 'Badge was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def badge_params
      params.require(:badge).permit(:name, :image, :description)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/ipaypals_helper.rb
module IpaypalsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/badges/_form.html.erb
<%= form_for(@badge) do |f| %>
  <% if @badge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
      <% @badge.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render 'form' %>

<%= link_to 'Show', @badge %> |
<%= link_to 'Back', badges_path %>

app/views/badges/index.html.erb
<h1>Listing badges</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @badges.each do |badge| %>
      <tr>
        <td><%= badge.name %></td>
        <td><%= badge.image %></td>
        <td><%= badge.description %></td>
        <td><%= link_to 'Show', badge %></td>
        <td><%= link_to 'Edit', edit_badge_path(badge) %></td>
        <td><%= link_to 'Destroy', badge, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Badge', new_badge_path %>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render 'form' %>

<%= link_to 'Back', badges_path %>

app/views/badges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @badge.name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @badge.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @badge.description %>
</p>

<%= link_to 'Edit', edit_badge_path(@badge) %> |
<%= link_to 'Back', badges_path %>