config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :tags_neededs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :fan_user_styles

  resources :fan_style_definitions

  resources :user_badges

  resources :badges

  match '/scoreColumns',:controller=>'rate_columns',:action=>'columnName',via:[:get,:post]
  match '/changeViewColumn',:controller=>'rate_columns',:action=>'addNewColumn',via:[:get,:post]
  resources :rate_columns

  resources :fan_rates

  match 'skills/:q',:controller=>'skill_neededs',:action=>'skillProject',via:[:get],to: 'skill_neededs#index'
  resources :skill_neededs

  resources :skill_lists
  

  match 'paypal/:q',:controller=>'ipaypals',:action=>'index',via:[:get],to: 'ipaypals#index'
  resources :ipaypals

  match '/listFiles',:controller=>'sessions',:action=>'listfiles',via:[:get,:post]
  match '/aut/google_oauth2',:controller=>'sessions',:action=>'perform_sync',via:[:get,:post]
  match '/aut/google_oauth2/callback',:controller=>'sessions',:action=>'perform_sync_callback',via:[:get,:post]
  match '/aut/reset',:controller=>'sessions',:action=>'perform_reset',via:[:get,:post]
  match '/aut/permission',:controller=>'sessions',:action=>'givePermissionToFolder',via:[:get,:post]
  match '/aut/filepermission',:controller=>'sessions',:action=>'givePermissionToFile',via:[:get,:post]
  resources :sessions

  match '/tab/remove',:controller=>'tabmanagers',:action=>'tab_remove',via:[:get,:post]
  resources :tabmanagers

  resources :license_types

  
  match '/getUserRating',:controller=>'fan_users',:action=>'getUserRating',via:[:get,:post]
  match '/registerProcess',:controller=>'fan_users',:action=>'registerProcess',via:[:get,:post]
  match '/loginProcess',:controller=>'fan_users',:action=>'logProcess',via:[:get,:post]
  match '/logoutProcess',:controller=>'fan_users',:action=>'logoutProcess',via:[:get,:post]

  match '/notifications',:controller=>'fan_users',:action=>'notifications',via:[:get,:post]
  
  match '/setUserRating',:controller=>'fan_users',:action=>'setUserRating',via:[:get,:post]
  match '/user-style/:q',:controller=>'fan_users',:action=>'setUserStyle',via:[:get],:to=>'fan_user_styles#index'
  resources :fan_users

  match '/setTaskWorker', :controller=>'fan_tasks',:action=>'claimTask',via:[:get,:post]
  match '/setDemoFile', :controller=>'fan_tasks',:action=>'assignDemoFile',via:[:get,:post]
  match '/setTaskFile', :controller=>'fan_tasks',:action=>'assignFanTask',via:[:get,:post]
  match '/setDeliveryFile', :controller=>'fan_tasks',:action=>'assignFinalFile',via:[:get,:post]
  match '/submitFilesToFanimate', :controller=>'fan_tasks',:action=>'submitTask',via:[:get,:post]
  match '/attachPermission', :controller=>'fan_tasks',:action=>'changePermission',via:[:get,:post]
  match '/attachReferences', :controller=>'fan_tasks',:action=>'attachReferences',via:[:get,:post]
  match '/getSharedFilesAsync', :controller=>'fan_tasks',:action=>'getSharedFilesAsync',via:[:get,:post]
  match '/acceptTask', :controller=>'fan_tasks',:action=>'acceptTask',via:[:get,:post]
  match '/rejectTask', :controller=>'fan_tasks',:action=>'rejectTask',via:[:get,:post]
  resources :fan_tasks

  match '/getProjectTasks', :controller=>'fan_projects',:action=>'getProjectTasks',via:[:get,:post]
  match '/getProjectTabs', :controller=>'fan_projects',:action=>'getProjectTabs',via:[:get,:post]
  resources :fan_projects

  resources :fan_pivot_tasks

  resources :fan_files

  match '/getCurrentCategory',:controller=>'fan_categories',:action=>'getCategory',via:[:get,:post]
  match '/setCurrentCategory',:controller=>'fan_categories',:action=>'setCategory',via:[:get,:post]
  resources :fan_categories

  match '/search/:q',:controller=>'welcome',:action=>'search',via:[:get],to: 'welcome#_edit'

  match '/schedule',:controller=>'welcome',:action=>'schedule',via:[:get]
  root 'welcome#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/fan_category.rb
class FanCategory < ActiveRecord::Base
end

app/models/fan_file.rb
class FanFile < ActiveRecord::Base
end

app/models/fan_pivot_task.rb
class FanPivotTask < ActiveRecord::Base
end

app/models/fan_project.rb
class FanProject < ActiveRecord::Base
end

app/models/fan_rate.rb
class FanRate < ActiveRecord::Base
end

app/models/fan_task.rb
class FanTask < ActiveRecord::Base
end

app/models/fan_user.rb
class FanUser < ActiveRecord::Base
end

app/models/fan_user_style.rb
class FanUserStyle < ActiveRecord::Base
end

app/models/history.rb
class History < ActiveRecord::Base
end

app/models/ipaypal.rb
class Ipaypal < ActiveRecord::Base
end

app/models/license_type.rb
class LicenseType < ActiveRecord::Base
end

app/models/rate_column.rb
class RateColumn < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/skill_list.rb
class SkillList < ActiveRecord::Base
end

app/models/skill_needed.rb
class SkillNeeded < ActiveRecord::Base
end

app/models/tabmanager.rb
class Tabmanager < ActiveRecord::Base
end

app/models/tags_needed.rb
class TagsNeeded < ActiveRecord::Base
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  before_action :set_history, only: [:show, :edit, :update, :destroy]

  # GET /histories
  # GET /histories.json
  def index
    @histories = History.all
  end

  # GET /histories/1
  # GET /histories/1.json
  def show
  end

  # GET /histories/new
  def new
    @history = History.new
  end

  # GET /histories/1/edit
  def edit
  end

  # POST /histories
  # POST /histories.json
  def create
    @history = History.new(history_params)

    respond_to do |format|
      if @history.save
        format.html { redirect_to @history, notice: 'History was successfully created.' }
        format.json { render :show, status: :created, location: @history }
      else
        format.html { render :new }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /histories/1
  # PATCH/PUT /histories/1.json
  def update
    respond_to do |format|
      if @history.update(history_params)
        format.html { redirect_to @history, notice: 'History was successfully updated.' }
        format.json { render :show, status: :ok, location: @history }
      else
        format.html { render :edit }
        format.json { render json: @history.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /histories/1
  # DELETE /histories/1.json
  def destroy
    @history.destroy
    respond_to do |format|
      format.html { redirect_to histories_url, notice: 'History was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_history
      @history = History.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def history_params
      params.require(:history).permit(:user_id, :task_id, :completed, :file_id, :due_time, :price)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/histories/_form.html.erb
<%= form_for(@history) do |f| %>
  <% if @history.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@history.errors.count, "error") %> prohibited this history from being saved:</h2>

      <ul>
      <% @history.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :task_id %><br>
    <%= f.number_field :task_id %>
  </div>
  <div class="field">
    <%= f.label :completed %><br>
    <%= f.number_field :completed %>
  </div>
  <div class="field">
    <%= f.label :file_id %><br>
    <%= f.text_field :file_id %>
  </div>
  <div class="field">
    <%= f.label :due_time %><br>
    <%= f.text_field :due_time %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/histories/edit.html.erb
<h1>Editing history</h1>

<%= render 'form' %>

<%= link_to 'Show', @history %> |
<%= link_to 'Back', histories_path %>

app/views/histories/index.html.erb
<h1>Listing histories</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Task</th>
      <th>Completed</th>
      <th>File</th>
      <th>Due time</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @histories.each do |history| %>
      <tr>
        <td><%= history.user_id %></td>
        <td><%= history.task_id %></td>
        <td><%= history.completed %></td>
        <td><%= history.file_id %></td>
        <td><%= history.due_time %></td>
        <td><%= history.price %></td>
        <td><%= link_to 'Show', history %></td>
        <td><%= link_to 'Edit', edit_history_path(history) %></td>
        <td><%= link_to 'Destroy', history, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New History', new_history_path %>

app/views/histories/new.html.erb
<h1>New history</h1>

<%= render 'form' %>

<%= link_to 'Back', histories_path %>

app/views/histories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @history.user_id %>
</p>

<p>
  <strong>Task:</strong>
  <%= @history.task_id %>
</p>

<p>
  <strong>Completed:</strong>
  <%= @history.completed %>
</p>

<p>
  <strong>File:</strong>
  <%= @history.file_id %>
</p>

<p>
  <strong>Due time:</strong>
  <%= @history.due_time %>
</p>

<p>
  <strong>Price:</strong>
  <%= @history.price %>
</p>

<%= link_to 'Edit', edit_history_path(@history) %> |
<%= link_to 'Back', histories_path %>