config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :tags_neededs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :fan_user_styles

  resources :fan_style_definitions

  resources :user_badges

  resources :badges

  match '/scoreColumns',:controller=>'rate_columns',:action=>'columnName',via:[:get,:post]
  match '/changeViewColumn',:controller=>'rate_columns',:action=>'addNewColumn',via:[:get,:post]
  resources :rate_columns

  resources :fan_rates

  match 'skills/:q',:controller=>'skill_neededs',:action=>'skillProject',via:[:get],to: 'skill_neededs#index'
  resources :skill_neededs

  resources :skill_lists
  

  match 'paypal/:q',:controller=>'ipaypals',:action=>'index',via:[:get],to: 'ipaypals#index'
  resources :ipaypals

  match '/listFiles',:controller=>'sessions',:action=>'listfiles',via:[:get,:post]
  match '/aut/google_oauth2',:controller=>'sessions',:action=>'perform_sync',via:[:get,:post]
  match '/aut/google_oauth2/callback',:controller=>'sessions',:action=>'perform_sync_callback',via:[:get,:post]
  match '/aut/reset',:controller=>'sessions',:action=>'perform_reset',via:[:get,:post]
  match '/aut/permission',:controller=>'sessions',:action=>'givePermissionToFolder',via:[:get,:post]
  match '/aut/filepermission',:controller=>'sessions',:action=>'givePermissionToFile',via:[:get,:post]
  resources :sessions

  match '/tab/remove',:controller=>'tabmanagers',:action=>'tab_remove',via:[:get,:post]
  resources :tabmanagers

  resources :license_types

  
  match '/getUserRating',:controller=>'fan_users',:action=>'getUserRating',via:[:get,:post]
  match '/registerProcess',:controller=>'fan_users',:action=>'registerProcess',via:[:get,:post]
  match '/loginProcess',:controller=>'fan_users',:action=>'logProcess',via:[:get,:post]
  match '/logoutProcess',:controller=>'fan_users',:action=>'logoutProcess',via:[:get,:post]

  match '/notifications',:controller=>'fan_users',:action=>'notifications',via:[:get,:post]
  
  match '/setUserRating',:controller=>'fan_users',:action=>'setUserRating',via:[:get,:post]
  match '/user-style/:q',:controller=>'fan_users',:action=>'setUserStyle',via:[:get],:to=>'fan_user_styles#index'
  resources :fan_users

  match '/setTaskWorker', :controller=>'fan_tasks',:action=>'claimTask',via:[:get,:post]
  match '/setDemoFile', :controller=>'fan_tasks',:action=>'assignDemoFile',via:[:get,:post]
  match '/setTaskFile', :controller=>'fan_tasks',:action=>'assignFanTask',via:[:get,:post]
  match '/setDeliveryFile', :controller=>'fan_tasks',:action=>'assignFinalFile',via:[:get,:post]
  match '/submitFilesToFanimate', :controller=>'fan_tasks',:action=>'submitTask',via:[:get,:post]
  match '/attachPermission', :controller=>'fan_tasks',:action=>'changePermission',via:[:get,:post]
  match '/attachReferences', :controller=>'fan_tasks',:action=>'attachReferences',via:[:get,:post]
  match '/getSharedFilesAsync', :controller=>'fan_tasks',:action=>'getSharedFilesAsync',via:[:get,:post]
  match '/acceptTask', :controller=>'fan_tasks',:action=>'acceptTask',via:[:get,:post]
  match '/rejectTask', :controller=>'fan_tasks',:action=>'rejectTask',via:[:get,:post]
  resources :fan_tasks

  match '/getProjectTasks', :controller=>'fan_projects',:action=>'getProjectTasks',via:[:get,:post]
  match '/getProjectTabs', :controller=>'fan_projects',:action=>'getProjectTabs',via:[:get,:post]
  resources :fan_projects

  resources :fan_pivot_tasks

  resources :fan_files

  match '/getCurrentCategory',:controller=>'fan_categories',:action=>'getCategory',via:[:get,:post]
  match '/setCurrentCategory',:controller=>'fan_categories',:action=>'setCategory',via:[:get,:post]
  resources :fan_categories

  match '/search/:q',:controller=>'welcome',:action=>'search',via:[:get],to: 'welcome#_edit'

  match '/schedule',:controller=>'welcome',:action=>'schedule',via:[:get]
  root 'welcome#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/fan_category.rb
class FanCategory < ActiveRecord::Base
end

app/models/fan_file.rb
class FanFile < ActiveRecord::Base
end

app/models/fan_pivot_task.rb
class FanPivotTask < ActiveRecord::Base
end

app/models/fan_project.rb
class FanProject < ActiveRecord::Base
end

app/models/fan_rate.rb
class FanRate < ActiveRecord::Base
end

app/models/fan_task.rb
class FanTask < ActiveRecord::Base
end

app/models/fan_user.rb
class FanUser < ActiveRecord::Base
end

app/models/fan_user_style.rb
class FanUserStyle < ActiveRecord::Base
end

app/models/history.rb
class History < ActiveRecord::Base
end

app/models/ipaypal.rb
class Ipaypal < ActiveRecord::Base
end

app/models/license_type.rb
class LicenseType < ActiveRecord::Base
end

app/models/rate_column.rb
class RateColumn < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/skill_list.rb
class SkillList < ActiveRecord::Base
end

app/models/skill_needed.rb
class SkillNeeded < ActiveRecord::Base
end

app/models/tabmanager.rb
class Tabmanager < ActiveRecord::Base
end

app/models/tags_needed.rb
class TagsNeeded < ActiveRecord::Base
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
end

app/controllers/tags_neededs_controller.rb
class TagsNeededsController < ApplicationController
  before_action :set_tags_needed, only: [:show, :edit, :update, :destroy]

  # GET /tags_neededs
  # GET /tags_neededs.json
  def index
    @tags_neededs = TagsNeeded.all
  end

  # GET /tags_neededs/1
  # GET /tags_neededs/1.json
  def show
  end

  # GET /tags_neededs/new
  def new
    @tags_needed = TagsNeeded.new
  end

  # GET /tags_neededs/1/edit
  def edit
  end

  # POST /tags_neededs
  # POST /tags_neededs.json
  def create
    @tags_needed = TagsNeeded.new(tags_needed_params)
    @project=FanProject.find_by_id(@tags_needed.project_id)
    
    respond_to do |format|
      if @tags_needed.save
        format.html { redirect_to "/fan_projects/"+@project.id.to_s+"/edit", notice: 'Skill needed was successfully created.' }
        format.json { render :show, status: :created, location: @tags_needed }
      else
        format.html { render :new }
        format.json { render json: @tags_needed.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags_neededs/1
  # PATCH/PUT /tags_neededs/1.json
  def update
    respond_to do |format|
      if @tags_needed.update(tags_needed_params)
        format.html { redirect_to @tags_needed, notice: 'Tags needed was successfully updated.' }
        format.json { render :show, status: :ok, location: @tags_needed }
      else
        format.html { render :edit }
        format.json { render json: @tags_needed.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags_neededs/1
  # DELETE /tags_neededs/1.json
  def destroy
    @tags_needed.destroy
    respond_to do |format|
      format.html { redirect_to tags_neededs_url, notice: 'Tags needed was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tags_needed
      @tags_needed = TagsNeeded.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tags_needed_params
      params.require(:tags_needed).permit(:task_id, :fan_style_definition_id, :project_id, :fan_style_text)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/tags_neededs_helper.rb
module TagsNeededsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/tags_neededs/_form.html.erb
<%= simple_form_for @tags_needed do |f| %>
<input type="hidden" name="tags_needed[project_id]" value="<%= @tags_needed.project_id %>">
<input type="hidden" name="tags_needed[task_id]" value="<%= @tags_needed.task_id %>">
  <% if @tags_needed.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tags_needed.errors.count, "error") %> prohibited this tags_needed from being saved:</h2>

      <ul>
      <% @tags_needed.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!-- <div class="field">
    <% f.label :task_id %><br>
    <% f.number_field :task_id %>
  </div> -->
  <div class="field">
    <%= f.input :fan_style_definition_id,:collection => FanStyleDefinition.all,:label_method => :name,:value_method => :id,:label => "Style" ,:include_blank => false %>
  </div>
  <!-- <div class="field">
    <% f.label :project_id %><br>
    <% f.number_field :project_id %>
  </div> -->
  <!-- <div class="field">
    <% f.label :fan_style_text %><br>
    <% f.text_field :fan_style_text %>
  </div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags_neededs/edit.html.erb
<h1>Editing tags_needed</h1>

<%= render 'form' %>

<%= link_to 'Show', @tags_needed %> |
<%= link_to 'Back', tags_neededs_path %>

app/views/tags_neededs/index.html.erb
<h1>Listing tags_neededs</h1>

<table>
  <thead>
    <tr>
      <th>Task</th>
      <th>Fan style definition</th>
      <th>Project</th>
      <th>Fan style text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags_neededs.each do |tags_needed| %>
      <tr>
        <td><%= tags_needed.task_id %></td>
        <td><%= tags_needed.fan_style_definition_id %></td>
        <td><%= tags_needed.project_id %></td>
        <td><%= tags_needed.fan_style_text %></td>
        <td><%= link_to 'Show', tags_needed %></td>
        <td><%= link_to 'Edit', edit_tags_needed_path(tags_needed) %></td>
        <td><%= link_to 'Destroy', tags_needed, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tags needed', new_tags_needed_path %>

app/views/tags_neededs/new.html.erb
<h1>New tags_needed</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_neededs_path %>

app/views/tags_neededs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @tags_needed.task_id %>
</p>

<p>
  <strong>Fan style definition:</strong>
  <%= @tags_needed.fan_style_definition_id %>
</p>

<p>
  <strong>Project:</strong>
  <%= @tags_needed.project_id %>
</p>

<p>
  <strong>Fan style text:</strong>
  <%= @tags_needed.fan_style_text %>
</p>

<%= link_to 'Edit', edit_tags_needed_path(@tags_needed) %> |
<%= link_to 'Back', tags_neededs_path %>