config/routes.rb
Rails.application.routes.draw do

  resources :histories

  resources :tags_neededs

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :fan_user_styles

  resources :fan_style_definitions

  resources :user_badges

  resources :badges

  match '/scoreColumns',:controller=>'rate_columns',:action=>'columnName',via:[:get,:post]
  match '/changeViewColumn',:controller=>'rate_columns',:action=>'addNewColumn',via:[:get,:post]
  resources :rate_columns

  resources :fan_rates

  match 'skills/:q',:controller=>'skill_neededs',:action=>'skillProject',via:[:get],to: 'skill_neededs#index'
  resources :skill_neededs

  resources :skill_lists
  

  match 'paypal/:q',:controller=>'ipaypals',:action=>'index',via:[:get],to: 'ipaypals#index'
  resources :ipaypals

  match '/listFiles',:controller=>'sessions',:action=>'listfiles',via:[:get,:post]
  match '/aut/google_oauth2',:controller=>'sessions',:action=>'perform_sync',via:[:get,:post]
  match '/aut/google_oauth2/callback',:controller=>'sessions',:action=>'perform_sync_callback',via:[:get,:post]
  match '/aut/reset',:controller=>'sessions',:action=>'perform_reset',via:[:get,:post]
  match '/aut/permission',:controller=>'sessions',:action=>'givePermissionToFolder',via:[:get,:post]
  match '/aut/filepermission',:controller=>'sessions',:action=>'givePermissionToFile',via:[:get,:post]
  resources :sessions

  match '/tab/remove',:controller=>'tabmanagers',:action=>'tab_remove',via:[:get,:post]
  resources :tabmanagers

  resources :license_types

  
  match '/getUserRating',:controller=>'fan_users',:action=>'getUserRating',via:[:get,:post]
  match '/registerProcess',:controller=>'fan_users',:action=>'registerProcess',via:[:get,:post]
  match '/loginProcess',:controller=>'fan_users',:action=>'logProcess',via:[:get,:post]
  match '/logoutProcess',:controller=>'fan_users',:action=>'logoutProcess',via:[:get,:post]

  match '/notifications',:controller=>'fan_users',:action=>'notifications',via:[:get,:post]
  
  match '/setUserRating',:controller=>'fan_users',:action=>'setUserRating',via:[:get,:post]
  match '/user-style/:q',:controller=>'fan_users',:action=>'setUserStyle',via:[:get],:to=>'fan_user_styles#index'
  resources :fan_users

  match '/setTaskWorker', :controller=>'fan_tasks',:action=>'claimTask',via:[:get,:post]
  match '/setDemoFile', :controller=>'fan_tasks',:action=>'assignDemoFile',via:[:get,:post]
  match '/setTaskFile', :controller=>'fan_tasks',:action=>'assignFanTask',via:[:get,:post]
  match '/setDeliveryFile', :controller=>'fan_tasks',:action=>'assignFinalFile',via:[:get,:post]
  match '/submitFilesToFanimate', :controller=>'fan_tasks',:action=>'submitTask',via:[:get,:post]
  match '/attachPermission', :controller=>'fan_tasks',:action=>'changePermission',via:[:get,:post]
  match '/attachReferences', :controller=>'fan_tasks',:action=>'attachReferences',via:[:get,:post]
  match '/getSharedFilesAsync', :controller=>'fan_tasks',:action=>'getSharedFilesAsync',via:[:get,:post]
  match '/acceptTask', :controller=>'fan_tasks',:action=>'acceptTask',via:[:get,:post]
  match '/rejectTask', :controller=>'fan_tasks',:action=>'rejectTask',via:[:get,:post]
  resources :fan_tasks

  match '/getProjectTasks', :controller=>'fan_projects',:action=>'getProjectTasks',via:[:get,:post]
  match '/getProjectTabs', :controller=>'fan_projects',:action=>'getProjectTabs',via:[:get,:post]
  resources :fan_projects

  resources :fan_pivot_tasks

  resources :fan_files

  match '/getCurrentCategory',:controller=>'fan_categories',:action=>'getCategory',via:[:get,:post]
  match '/setCurrentCategory',:controller=>'fan_categories',:action=>'setCategory',via:[:get,:post]
  resources :fan_categories

  match '/search/:q',:controller=>'welcome',:action=>'search',via:[:get],to: 'welcome#_edit'

  match '/schedule',:controller=>'welcome',:action=>'schedule',via:[:get]
  root 'welcome#index'

end

app/models/badge.rb
class Badge < ActiveRecord::Base
end

app/models/fan_category.rb
class FanCategory < ActiveRecord::Base
end

app/models/fan_file.rb
class FanFile < ActiveRecord::Base
end

app/models/fan_pivot_task.rb
class FanPivotTask < ActiveRecord::Base
end

app/models/fan_project.rb
class FanProject < ActiveRecord::Base
end

app/models/fan_rate.rb
class FanRate < ActiveRecord::Base
end

app/models/fan_task.rb
class FanTask < ActiveRecord::Base
end

app/models/fan_user.rb
class FanUser < ActiveRecord::Base
end

app/models/fan_user_style.rb
class FanUserStyle < ActiveRecord::Base
end

app/models/history.rb
class History < ActiveRecord::Base
end

app/models/ipaypal.rb
class Ipaypal < ActiveRecord::Base
end

app/models/license_type.rb
class LicenseType < ActiveRecord::Base
end

app/models/rate_column.rb
class RateColumn < ActiveRecord::Base
end

app/models/session.rb
class Session < ActiveRecord::Base
end

app/models/skill_list.rb
class SkillList < ActiveRecord::Base
end

app/models/skill_needed.rb
class SkillNeeded < ActiveRecord::Base
end

app/models/tabmanager.rb
class Tabmanager < ActiveRecord::Base
end

app/models/tags_needed.rb
class TagsNeeded < ActiveRecord::Base
end

app/models/user_badge.rb
class UserBadge < ActiveRecord::Base
end

app/controllers/fan_user_styles_controller.rb
class FanUserStylesController < ApplicationController
  before_action :set_fan_user_style, only: [:show, :edit, :update, :destroy]

  # GET /fan_user_styles
  # GET /fan_user_styles.json
  def index
    puts "======"
    puts params.inspect
    puts "======"
    @fan_user_style = FanUserStyle.new
    @fan_user_style.user_id=params[:q]
    @fan_user_styles = FanUserStyle.where(:user_id=>params[:q])
    render :layout => false
  end
  def style
    @fan_style_definitions = FanStyleDefinition.all
    render :layout => false
  end

  # GET /fan_user_styles/1
  # GET /fan_user_styles/1.json
  def show
  end

  # GET /fan_user_styles/new
  def new
    @fan_user_style = FanUserStyle.new
  end

  # GET /fan_user_styles/1/edit
  def edit
  end

  # POST /fan_user_styles
  # POST /fan_user_styles.json
  def create
    @fan_user_style = FanUserStyle.new(fan_user_style_params)

    respond_to do |format|
      if @fan_user_style.save
        format.html { redirect_to "/fan_rates", notice: 'Fan user style was successfully created.' }
        format.json { render :show, status: :created, location: @fan_user_style }
      else
        format.html { render :new }
        format.json { render json: @fan_user_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fan_user_styles/1
  # PATCH/PUT /fan_user_styles/1.json
  def update
    respond_to do |format|
      if @fan_user_style.update(fan_user_style_params)
        format.html { redirect_to @fan_user_style, notice: 'Fan user style was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan_user_style }
      else
        format.html { render :edit }
        format.json { render json: @fan_user_style.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fan_user_styles/1
  # DELETE /fan_user_styles/1.json
  def destroy
    @fan_user_style.destroy
    respond_to do |format|
      format.html { redirect_to fan_user_styles_url, notice: 'Fan user style was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan_user_style
      @fan_user_style = FanUserStyle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_user_style_params
      params.require(:fan_user_style).permit(:style_definition_id, :user_id)
    end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/fan_user_styles_helper.rb
module FanUserStylesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fan_user_styles/_form.html.erb
<%= simple_form_for @fan_user_style do |f| %>
<input type="hidden" name="fan_user_style[user_id]" value="<%= @fan_user_style.user_id %>">
  <% if @fan_user_style.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fan_user_style.errors.count, "error") %> prohibited this fan_user_style from being saved:</h2>

      <ul>
      <% @fan_user_style.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% f.label :style_definition_id %><br>
    
    <%= f.input :style_definition_id,:collection => FanStyleDefinition.all,:label_method => :name,:value_method => :id,:label => "Style" ,:include_blank => false %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <% f.number_field :user_id %>
    <% if @fan_user_style.user_id!=nil %>
      <%= FanUser.find_by_id(@fan_user_style.user_id).username %> 
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fan_user_styles/edit.html.erb
<h1>Editing fan_user_style</h1>

<%= render 'form' %>

<%= link_to 'Show', @fan_user_style %> |
<%= link_to 'Back', fan_user_styles_path %>

app/views/fan_user_styles/index.html.erb
<div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Skill filter</h4>
      </div>
      <div class="modal-body">



<table class="table table-striped">
  <thead>
    <tr>
      <th>Style definition</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fan_user_styles.each do |fan_user_style| %>
      <tr>
        <td><%= FanStyleDefinition.find_by_id(fan_user_style.style_definition_id).name %></td>
        <td><%= FanUser.find_by_id(fan_user_style.user_id).username %></td>
        <td><%= link_to 'Show', fan_user_style %></td>
        <td><%= link_to 'Edit', edit_fan_user_style_path(fan_user_style) %></td>
        <td><%= link_to 'Destroy', fan_user_style, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<h4>Add a new style to this user</h4>
<%= render "fan_user_styles/form" %>

</div>
      <div class="modal-footer">
        <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button> -->
      </div>
    </div>
<% link_to 'New Fan user style', new_fan_user_style_path %>

app/views/fan_user_styles/new.html.erb
<h1>New fan_user_style</h1>

<%= render 'form' %>

<%= link_to 'Back', fan_user_styles_path %>

app/views/fan_user_styles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Style definition:</strong>
  <%= @fan_user_style.style_definition_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @fan_user_style.user_id %>
</p>

<%= link_to 'Edit', edit_fan_user_style_path(@fan_user_style) %> |
<%= link_to 'Back', fan_user_styles_path %>